/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import conexion.ConexionBD;

import java.sql.*;
import javax.swing.*;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

/**
 *
 * @author JHON
 */
public class GenerarReceta extends javax.swing.JFrame {

    private int idPaciente = 1; // o recibirlo desde otro formulario
    private String nombrePaciente = "Paciente de Prueba";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarReceta.class.getName());

    /**
     * Creates new form GenerarReceta
     */
    public GenerarReceta() {
        initComponents();
        cargarMedicamentosDesdeBD();

    }
    //obtenerNombrePaciente();
    //descontarMedicamentoDeInventario();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMedicamentos = new javax.swing.JComboBox<>();
        txtDosis = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        btnImprimirReceta = new javax.swing.JButton();
        lblNombrePaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbMedicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosisActionPerformed(evt);
            }
        });

        txtFrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrecuenciaActionPerformed(evt);
            }
        });

        btnImprimirReceta.setText("Imprimir Receta");
        btnImprimirReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRecetaActionPerformed(evt);
            }
        });

        lblNombrePaciente.setText("Nombre Paciente");

        jLabel2.setText("Dosis");

        jLabel3.setText("Frecuencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDosis)
                                .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnImprimirReceta))
                            .addComponent(jLabel4))
                        .addContainerGap(168, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cbMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnImprimirReceta)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRecetaActionPerformed
        generarPDFReceta();
    }//GEN-LAST:event_btnImprimirRecetaActionPerformed

    private void txtDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDosisActionPerformed

    private void txtFrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrecuenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GenerarReceta().setVisible(true));
    }

    /////////////////////////////////////////////////////////////
    private void cargarMedicamentosDesdeBD() {
        ConexionBD conexion = new ConexionBD();
        Connection conn = conexion.establecerConexion();

        try {
            String sql = "SELECT nombre FROM Medicamentos WHERE stock > 0";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            while (rs.next()) {
                model.addElement(rs.getString("nombre"));
            }
            cbMedicamentos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar medicamentos: " + ex.getMessage());
        }
    }

    /////////////////////////////////////////////////////////
    private void generarPDFReceta() {
        String medicamento = cbMedicamentos.getSelectedItem().toString();
        String dosis = txtDosis.getText();
        String frecuencia = txtFrecuencia.getText();

        if (dosis.isEmpty() || frecuencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Receta_" + idPaciente + ".pdf"));
            document.open();

            Font fontTitulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Paragraph titulo = new Paragraph("RECETA MÉDICA", fontTitulo);
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Paciente: " + obtenerNombrePaciente(idPaciente)));
            document.add(new Paragraph("Fecha: " + new java.util.Date().toString()));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Medicamento: " + medicamento));
            document.add(new Paragraph("Dosis: " + dosis));
            document.add(new Paragraph("Frecuencia: " + frecuencia));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Instrucciones:"));
            document.add(new Paragraph("- No exceder la dosis recomendada"));
            document.add(new Paragraph("- Consultar en caso de efectos adversos"));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Firma del médico: _________________________"));

            document.close();
            JOptionPane.showMessageDialog(this, "Receta generada como: Receta_" + idPaciente + ".pdf");

            descontarMedicamentoDeInventario(medicamento);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage());
        }
    }

    //////////////////////////////////////////////////////////
    
   private String obtenerNombrePaciente(int idPaciente) {
        ConexionBD conexion = new ConexionBD();
        Connection conn = conexion.establecerConexion();

        try {
            String sql = "SELECT nombre FROM Pacientes WHERE id_paciente = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, idPaciente);
            ResultSet rs = stmt.executeQuery();

            return rs.next() ? rs.getString("nombre") : "Paciente desconocido";
        } catch (SQLException ex) {
            return "Error al cargar datos";
        }
    }

    ///////////////////////////////////////////////////////////////
    private void descontarMedicamentoDeInventario(String medicamento) {
        ConexionBD conexion = new ConexionBD();
        Connection conn = conexion.establecerConexion();

        try {
            String sql = "UPDATE Medicamentos SET stock = stock - 1 WHERE nombre = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, medicamento);
            stmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar inventario: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirReceta;
    private javax.swing.JComboBox<String> cbMedicamentos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtFrecuencia;
    // End of variables declaration//GEN-END:variables
}
